# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nrrdFCNxTWcEhZR1_t_hq0SkVU_Atfcm

```markdown
# ATM Machine Simulation
```
"""

from datetime import datetime, timedelta

def atm_simulation():
    # Initial account details
    pin = "1234"
    balance = 10000

    # Transaction history: date, type, amount, current_balance
    # Pre-populate with some sample transactions for statement demonstration
    transactions = [
        {'date': datetime.now() - timedelta(days=360), 'type': 'deposit', 'amount': 500, 'balance_after': 500},
        {'date': datetime.now() - timedelta(days=300), 'type': 'withdraw', 'amount': 100, 'balance_after': 400},
        {'date': datetime.now() - timedelta(days=45), 'type': 'deposit', 'amount': 2000, 'balance_after': 2400},
        {'date': datetime.now() - timedelta(days=10), 'type': 'withdraw', 'amount': 300, 'balance_after': 2100},
        {'date': datetime.now() - timedelta(days=5), 'type': 'deposit', 'amount': 7900, 'balance_after': 10000}
    ]

    print("Welcome to the ATM!")

    # PIN validation
    attempts = 0
    while attempts < 3:
        entered_pin = input("Please enter your 4-digit PIN: ")
        if entered_pin == pin:
            print("PIN accepted. You can now perform transactions.")
            break
        else:
            attempts += 1
            print(f"Invalid PIN. {3 - attempts} attempts remaining.")
    else:
        print("Too many incorrect attempts. Your card has been blocked. Please contact your bank.")
        return

    # Main ATM loop
    while True:
        print("\n--- ATM Menu ---")
        print("1. Check Balance")
        print("2. Withdraw")
        print("3. Deposit")
        print("4. Change PIN")
        print("5. Print Statement")
        print("6. Customer Support")
        print("7. Exit")

        choice = input("Please choose an option: ")

        if choice == '1':
            print(f"Your current balance is: ${balance:.2f}")
        elif choice == '2':
            try:
                amount = float(input("Enter amount to withdraw: "))
                if amount <= 0:
                    print("Withdrawal amount must be positive.")
                elif amount > balance:
                    print("Insufficient funds.")
                else:
                    balance -= amount
                    transactions.append({'date': datetime.now(), 'type': 'withdraw', 'amount': amount, 'balance_after': balance})
                    print(f"${amount:.2f} withdrawn successfully. Your new balance is: ${balance:.2f}")
            except ValueError:
                print("Invalid amount. Please enter a number.")
        elif choice == '3':
            try:
                amount = float(input("Enter amount to deposit: "))
                if amount <= 0:
                    print("Deposit amount must be positive.")
                else:
                    balance += amount
                    transactions.append({'date': datetime.now(), 'type': 'deposit', 'amount': amount, 'balance_after': balance})
                    print(f"${amount:.2f} deposited successfully. Your new balance is: ${balance:.2f}")
            except ValueError:
                print("Invalid amount. Please enter a number.")
        elif choice == '4':
            old_pin = input("Enter your old PIN: ")
            if old_pin == pin:
                new_pin = input("Enter your new 4-digit PIN: ")
                confirm_new_pin = input("Confirm your new PIN: ")
                if new_pin == confirm_new_pin and len(new_pin) == 4 and new_pin.isdigit():
                    pin = new_pin
                    print("PIN changed successfully!")
                else:
                    print("New PINs do not match or are invalid (must be 4 digits).")
            else:
                print("Incorrect old PIN. PIN change failed.")
        elif choice == '5':
            print("\n--- Statement Options ---")
            print("1. Last 1 Month")
            print("2. Last 1 Year")
            print("3. All Transactions")
            statement_choice = input("Choose statement period: ")

            now = datetime.now()
            filtered_transactions = []

            if statement_choice == '1':
                one_month_ago = now - timedelta(days=30)
                filtered_transactions = [t for t in transactions if t['date'] >= one_month_ago]
                print("\n--- Last 1 Month Statement ---")
            elif statement_choice == '2':
                one_year_ago = now - timedelta(days=365)
                filtered_transactions = [t for t in transactions if t['date'] >= one_year_ago]
                print("\n--- Last 1 Year Statement ---")
            elif statement_choice == '3':
                filtered_transactions = transactions
                print("\n--- All Transactions Statement ---")
            else:
                print("Invalid statement option.")
                continue

            if filtered_transactions:
                # Sort transactions by date for better readability
                filtered_transactions.sort(key=lambda x: x['date'])
                print("Date         | Type     | Amount    | Balance After")
                print("---------------------------------------------------")
                for t in filtered_transactions:
                    print(f"{t['date'].strftime('%Y-%m-%d')} | {t['type']:<8} | ${t['amount']:<8.2f} | ${t['balance_after']:.2f}")
            else:
                print("No transactions found for the selected period.")

        elif choice == '6':
            print("\n--- Customer Support ---")
            print("For assistance, please call our toll-free number: 1-800-ATM-HELP (1-800-286-4357)")
            print("Or visit our website: www.fakeatm.com/support")
            print("Our customer service representatives are available 24/7.")

        elif choice == '7':
            print("Thank you for using the ATM. Goodbye!")
            break
        else:
            print("Invalid choice. Please select a valid option from the menu.")

# Run the ATM simulation
atm_simulation()