# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nrrdFCNxTWcEhZR1_t_hq0SkVU_Atfcm
"""

world_cup_matches = [
    {
        'year': 2002,
        'team1': 'Brazil',
        'team2': 'Germany',
        'score': '2-0',
        'winner': 'Brazil',
        'stage': 'Final'
    },
    {
        'year': 2006,
        'team1': 'Italy',
        'team2': 'France',
        'score': '1-1 (5-3 pens)',
        'winner': 'Italy',
        'stage': 'Final'
    },
    {
        'year': 2010,
        'team1': 'Spain',
        'team2': 'Netherlands',
        'score': '1-0 (a.e.t.)',
        'winner': 'Spain',
        'stage': 'Final'
    },
    {
        'year': 2014,
        'team1': 'Germany',
        'team2': 'Argentina',
        'score': '1-0 (a.e.t.)',
        'winner': 'Germany',
        'stage': 'Final'
    },
    {
        'year': 2018,
        'team1': 'France',
        'team2': 'Croatia',
        'score': '4-2',
        'winner': 'France',
        'stage': 'Final'
    },
    {
        'year': 2022,
        'team1': 'Argentina',
        'team2': 'France',
        'score': '3-3 (4-2 pens)',
        'winner': 'Argentina',
        'stage': 'Final'
    },
    {
        'year': 2026,
        'team1': 'TBD',
        'team2': 'TBD',
        'score': 'TBD',
        'winner': 'TBD',
        'stage': 'Final (Future)'
    },
    {
        'year': 2030,
        'team1': 'TBD',
        'team2': 'TBD',
        'score': 'TBD',
        'winner': 'TBD',
        'stage': 'Final (Future)'
    }
]

print("World Cup match data updated.")

def get_matches_by_year(year):
    """Displays World Cup matches for a given year."""
    found_matches = [match for match in world_cup_matches if match['year'] == year]

    if found_matches:
        print(f"\n--- World Cup Matches from {year} ---")
        for match in found_matches:
            print(f"  Stage: {match['stage']}")
            print(f"  {match['team1']} vs {match['team2']} | Score: {match['score']} | Winner: {match['winner']}")
            print("-------------------------------------")
    else:
        print(f"\nNo World Cup matches found for the year {year}.")

# Get user input for the year
try:
    search_year = int(input("Enter the World Cup year you want to search (e.g., 2022): "))
    get_matches_by_year(search_year)
except ValueError:
    print("Invalid input. Please enter a valid year (a number).")