# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLSIA7gzfQqyarh3I1kKahvcPM54G28V
"""

class Student:
    def __init__(self):
        self.name = ""
        self.roll_number = ""
        self.marks = []

    def get_data(self):
        """Accepts student details from the user."""
        self.name = input("Enter Student Name: ")
        self.roll_number = input("Enter Roll Number: ")

        # Collect marks for 3 subjects
        self.marks = []
        print("Enter marks for 3 subjects:")
        for i in range(1, 4):
            while True:
                try:
                    score = float(input(f"  Subject {i}: "))
                    if 0 <= score <= 100:
                        self.marks.append(score)
                        break
                    else:
                        print("  Please enter marks between 0 and 100.")
                except ValueError:
                    print("  Invalid input. Please enter a number.")

    def calculate_percentage(self):
        """Calculates and returns the percentage based on the 3 subjects."""
        if not self.marks:
            return 0.0
        total_marks = sum(self.marks)
        # Assuming each subject is out of 100
        percentage = (total_marks / 300) * 100
        return percentage

    def display_data(self):
        """Displays the student's complete profile and performance."""
        print("\n" + "="*30)
        print(f"STUDENT CARD: {self.name.upper()}")
        print("="*30)
        print(f"Roll Number : {self.roll_number}")
        print(f"Marks       : Subject 1: {self.marks[0]}, Subject 2: {self.marks[1]}, Subject 3: {self.marks[2]}")
        print(f"Percentage  : {self.calculate_percentage():.2f}%")
        print("="*30)


# --- Demonstration of the System ---
if __name__ == "__main__":
    print("--- Welcome to the Student Information System ---\n")

    # Create an instance of the Student class
    student1 = Student()

    # Gather information
    student1.get_data()

    # Display the results
    student1.display_data()